profile:
  default: development
project:
  type: website
  pre-render:
    - ./pre-render.py
  post-render:
    - ./post-render.py
  render:
    - "RESUME.md"
website:
  page-footer:
    border: true
    background: dark
    center: 
      - text: "<b>Download PDF</b>"
        href: /index.pdf
format-links: false
format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles.css
    link-external-newwindow: true
    canonical-url: true
  pdf: default
resources:
  - CNAME



